import styled from "styled-components";

export const Container = styled.div`
  margin-top: 150px;
  padding: 0 120px;

  @media screen and (max-width: 720px){
  display: flex;
  align-items: center;
  flex-direction: column;
}

  p{
    color:#fff;
    font-size: 42px;
  }

  span{
    color: ${({ theme }) => theme.colors.primary[300]};
    font-weight: bold;
    box-shadow: 1px;
  }

  h1{
    color:#fff;
  }

  .devHome{
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .function{
    font-size: 42px;
    margin-top: 35px;
  }

  .photo{
    img{
      border-radius: 50%;
      width: 250px;
    }

    @media (max-width:600px) {
      img{
        display: none;
      }
    }
  }

  .rotate-center {
  -webkit-animation: rotate-center 16s linear infinite both;
  animation: rotate-center 16s linear infinite both;
  /* ----------------------------------------------
 * Generated by Animista on 2023-3-21 14:8:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
  @-webkit-keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
              transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
              transform: rotate(360deg);
    }
  }
  @keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
              transform: rotate(0);
    }
    100% {
      -webkit-transform: rotate(360deg);
              transform: rotate(360deg);
    }
  }

}

  .introduceMyself{
    margin-top: 80px;
    display: flex;
    align-items: center;
    flex-direction: column;

    span{
      font-size: 40px;
      color:#fff;

      @media screen and (max-width: 720px){
        text-align: center;
    }
    }

    .emphasisTitle{
      font-size: 40px;
      color:${({ theme }) => theme.colors.primary[500]};
    }

    p{
      margin-top: 8px;
      font-size: 24px;
      @media screen and (max-width: 720px){
        text-align: center;
        margin-bottom: 24px;
    }
    }
    .description{
      .emphasis{
        font-size: 24px;
        color:${({ theme }) => theme.colors.primary[500]};
      }
    }
  }

  .socialMedias{
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 48px;

    span{
      color: #fff;
    }

    .findMeOn{
      font-size: 32px;
    }
    .socialMediaDescription{
      font-size: 16px;
    }

    .social{
      a{
        text-decoration: none;
        color: #fff;
        font-size: 32px;
        padding: 8px;
      }
    }
  }

`;
